apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
    name: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create namespace first
---